### PR TITLE
Update sbt-extras script upon release

### PR DESCRIPTION
**Pull request by alexarchambault**

### CODE REVIEW

**Comment by dwijnand** [comment]
Perhaps the bash script could read the sbt-launcher version from project/build.properties instead of requiring an update in the bash script?

**Comment by dwijnand** [comment]
That might also be a better way to incrementally switch sbt-extras to coursier/sbt-launcher too, instead of the bash script option flags.

**Comment by alexarchambault** [comment]
It could be read from `project/build.properties` too.

This PR updates the _default_ version of the launcher. For now, I feel I'd prefer users not to have to know about the launcher version, and have the script select a sensible one. IMO, the launcher is just an extension of the script, it's not a problem if both are tied.

**Comment by alexarchambault** [comment]
But yes, reading the version from `project/build.properties`, or even reading whether the coursier-based launcher should be used from there, would be nice (and offer a convenient way to switch to it).

**Comment by dwijnand** [comment]
(after-comment: I'm just writing down my thoughts and sharing some history)

So sbt.version is in the repo so that the build behaviour is tied to a specific version of sbt.  Historically it was said that _any_ sbt-launcher was forward and backwards compatible with the version defined in sbt.version, so you didn't even have to update your sbt-launcher (unless you wanted to).  It was a big of an argument, but sbt-extras held the opinion that it was safer to use the sbt-launcher of version X when sbt.version was set to X (e.g sbt-launcher v1.2.8 if sbt.version=1.2.8).

So in github.com/sbt world it just means you can keep using the same sbt-extras script and it'll use the sbt.version of each build.

With the introduction of coursier/sbt-launcher I don't think we want to start making users have to micro-manage which version of sbt-extras they have, which is why I'm suggesting we put it in `project/build.properties`.

So I like the solution here to update the fallback version, but all I'm concerned about is it shouldn't start requiring users worry about their bash script version (which is unversioned, btw - there's an issue thread on that)

**Comment by alexarchambault** [comment]
That's good point. I agree the sbt-launcher version should definitely be read from `project/build.properties` if it's in it, so that users aren't required to download the latest sbt-extras script too often.

**Comment by dwijnand** [comment]
I'd be happy to land that change in upstream sbt-extras, btw, if you want to PR that.

**Comment by alexarchambault** [comment]
Cool, I'll send something soon then.

**Pull request merged**
